player:
    thirst:
        enabled: true
        ticks: 420
        refill: 20
    visibility:
        enabled: true
        ticks: 10
    health:
        start: 20
        regen: false
    death:
        zombie: true
        inventory: true
    op:
        is_god: true


custom_spawning:
    enabled: true
    zombie_seconds: 180


items:
    end_grenade:
        enabled: true
        radius: 3
    chest:
        key: 131

world:
#    single_world:
#        enabled: false
#        world_name: your_world_name_here
    protect:
        from_explosions: true
        from_blocks : true
